### ISSUE TITLE
KeepAlive包裹组件显示空白

### ISSUE THREAD

**Issue by doveq** [CJY0208/react-activation#200]
KeepAlive包裹组件显示空白，环境是：

```
"react": "^18.1.0",
"react-activation": "^0.11.2",
"react-router-dom": "^6.3.0",
"typescript": "^4.7.2",
```

使用方式如下，显示的 index 页面是空白页，请问如何解决是使用方式有问题吗？谢谢。

```
...
import KeepAlive, { AliveScope } from 'react-activation'
....

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <StoreContext.Provider value={StoreData}>
      <AliveScope>
      <BrowserRouter>
        <Routes>
          <Route path="/login" element={<Login />} />
          <Route path='/' element={<Frame body={<KeepAlive when={true} cacheKey="page_index"><Index /></KeepAlive>} />} />
        </Routes>
      </BrowserRouter>
      </AliveScope>
    </StoreContext.Provider>
  </React.StrictMode>
);

```

**Comment by doveq** [comment]
测试发现，如果直接访问 http://127.0.0.1 就是空白页， 如果我先访问 http://127.0.0.1/login 再点击跳转到 / 则显示正常。 但是会报错：

```
Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the ProviderBridge component.
    at ConsumerWrapper (http://106.54.8.57:8001/static/js/bundle.js:57180:5)
    at RecursiveConsumerBridge (http://106.54.8.57:8001/static/js/bundle.js:57284:5)
    at LazyBridge (http://106.54.8.57:8001/static/js/bundle.js:57409:5)
    at ErrorThrower (http://106.54.8.57:8001/static/js/bundle.js:57498:5)
    at Acceptor (http://106.54.8.57:8001/static/js/bundle.js:57562:18)
    at NodeKey (http://106.54.8.57:8001/static/js/bundle.js:89406:5)
    at HookExpand (http://106.54.8.57:8001/static/js/bundle.js:58408:26)
    at div
    at div
    at Frame (http://106.54.8.57:8001/static/js/bundle.js:471:81)
    at Routes (http://106.54.8.57:8001/static/js/bundle.js:91589:5)
    at Router (http://106.54.8.57:8001/static/js/bundle.js:91522:15)
    at BrowserRouter (http://106.54.8.57:8001/static/js/bundle.js:90331:5)
    at FakeScopeProvider (http://106.54.8.57:8001/static/js/bundle.js:56788:5)
    at AliveScopeProvider$1 (http://106.54.8.57:8001/static/js/bundle.js:56894:23)
    at AliveScope (http://106.54.8.57:8001/static/js/bundle.js:58048:5)
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react.development.js:209
error @ react.development.js:183
warnNoop @ react.development.js:225
enqueueSetState @ react.development.js:296
Component.setState @ react.development.js:354
（匿名） @ ProviderBridge.js:26
（匿名） @ ConsumerWrapper.js:23
run @ run.js:26
ConsumerWrapper @ ConsumerWrapper.js:23
constructClassInstance @ react-dom.development.js:14323
updateClassComponent @ react-dom.development.js:19688
beginWork @ react-dom.development.js:21611
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
（匿名） @ react-dom.development.js:25651
```

**Comment by doveq** [comment]
关闭 StrictMode 正常了，是暂时不支持StrictMode吗

**Comment by CJY0208** [comment]
是的，StrictMode 有意触发了多次渲染来迫使开发者发现代码的设计缺陷，但也影响了 keep-alive 的工作流程

**Comment by doveq** [comment]
我之前有看到说 react18 开发模式会渲染2次，如果编译发布就不会多次渲染，我是不是可以在build 时加上 StrictMode ？

**Comment by CJY0208** [comment]
build 模式加 StrictMode 好像没太大意义了，可以看看是否有必要一定使用 StrictMode
